# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'MajalahKeuangan' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for MajalahKeuangan
  pod 'Firebase/Core', '~> 6.3.0'
  pod 'GoogleIDFASupport', '~> 3.14.0'
  pod 'Firebase/Auth', '~> 6.3.0'
  pod 'GoogleSignIn', '~> 4.4.0'
  pod 'TwitterKit', '~> 3.3.0'
  pod 'AppAuth', '~> 0.95.0'

  pod 'React', :path => '../node_modules/react-native'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  # React-Native is not great about React double-including from the Podfile
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end

      # It removes React & Yoga from the Pods project, as it is already included in the main project.
      targets_to_ignore = %w(React yoga)
      if targets_to_ignore.include? target.name
        target.remove_from_project
      end
    end
  end

  target 'MajalahKeuanganTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'MajalahKeuangan-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MajalahKeuangan-tvOS

  target 'MajalahKeuangan-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
