# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'MajalahKeuangan' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MajalahKeuangan
  pod 'Firebase/Core', '~> 6.3.0'
  pod 'Firebase/Auth', '~> 6.3.0'
  pod 'GoogleSignIn', '~> 4.4.0'
  pod 'TwitterKit', '~> 3.3.0'

  target 'MajalahKeuanganTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'MajalahKeuangan-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MajalahKeuangan-tvOS

  target 'MajalahKeuangan-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
